### ISSUE TITLE
Recommended: Separate widget class

### ISSUE THREAD

**Issue by justintadlock** [quotepro/quotepro-insurance-widget#8]
I'd recommend separating the widget class and the "plugin" stuff into two separate classes.  The widget class should have a very specific purposes of handling the widget and nothing else.  Code that's not directly related to that should be separated into its own class for setting up other plugin items.

This is just what I'd call good coding practice.  Everything should have its own purpose.  That purpose should be limited in scope.

I'd like to point you to one of my own plugins because they're very much alike in how they should function.  It should give you some ideas about what I'm talking about: https://github.com/justintadlock/widgets-reloaded

**Comment by b2k** [comment]
I’m not sure what you’re asking me to change here. The plugin only exists to enable the widget.

Incidentally, since this is my first plugin I started with the widget boilerplate. https://github.com/tommcfarlin/WordPress-Widget-Boilerplate https://github.com/tommcfarlin/WordPress-Widget-Boilerplate. Needless to say, I’m disappointed to find that it did not follow best practices for widget plugins.

**Comment by justintadlock** [comment]
Sorry about the late reply.  I took most of yesterday off (birthday).

Basically, you're extending the `WP_Widget` class.  That's good.  That's what you need to do to create widgets.  However, the plugin is more than just the widget itself.  Only certain parts of the code belong within the class that extends `WP_Widget`.

Specifically, the class that extends the `WP_Widget` class should have four methods:
- `Class_Name::__construct()`
- `Class_Name::widget()`
- `Class_Name::update()`
- `Class_Name::form()`

That's the actual widget.  Any other methods (or code within the class) that doesn't deal directly with registering or creating the widget should be separated.
